---
driver:
  name: docker
  hostname: backupninja.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: backupninja
  grains:
    noservices: True
  dependencies:
    - name: linux
      repo: git
      source: https://github.com/salt-formulas/salt-formula-linux
  state_top:
    base:
      "*":
        - backupninja
  pillars:
    top.sls:
      base:
        "*":
          - backupninja

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: server_rdiff
    provisioner:
      pillars-from-files:
        backupninja.sls: tests/pillar/server_rdiff.sls

  - name: client_rsync
    provisioner:
      pillars-from-files:
        backupninja.sls: tests/pillar/client_rsync.sls

  - name: client_rsync_backup_times
    provisioner:
      pillars-from-files:
        backupninja.sls: tests/pillar/client_rsync_backup_times.sls

  - name: client_s3
    provisioner:
      pillars-from-files:
        backupninja.sls: tests/pillar/client_s3.sls

  - name: client_s3_disabled_auto
    provisioner:
      pillars-from-files:
        backupninja.sls: tests/pillar/client_s3_disabled_auto.sls

  - name: client_webdav
    provisioner:
      pillars-from-files:
        backupninja.sls: tests/pillar/client_webdav.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
